#define COMPONENT ui
#include "\z\TER_MFU\addons\main\script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE

#ifdef DEBUG_ENABLED_UI
    #define DEBUG_MODE_FULL
#endif
    #ifdef DEBUG_SETTINGS_OTHER
    #define DEBUG_SETTINGS DEBUG_SETTINGS_UI
#endif

#include "\z\TER_MFU\addons\main\script_macros.hpp"
#include "\z\TER_MFU\addons\main\script_macros_common.hpp"

#include "\a3\3den\UI\resincl.inc"
#include "\a3\3den\UI\macros.inc"

#define UI_SCRIPT(NAME) NAME##_script
#ifdef DEBUG_MODE_FULL
    #define INIT_DISPLAY(NAME,PATH) \
        onLoad = ["onLoad",_this,#NAME,'##PATH##'] call compile preprocessfilelinenumbers QUOTE(z\TER_MFU\addons\ui\scripts\NAME.sqf); \
        onUnload = ["onUnload",_this,#NAME,'##PATH##'] call compile preprocessfilelinenumbers QUOTE(z\TER_MFU\addons\ui\scripts\NAME.sqf);
    #define UI_SCRIPT(NAME) (compile preprocessfilelinenumbers QUOTE(z\TER_MFU\addons\ui\scripts\NAME.sqf))
#endif

#define COLOR_DEBUG {1,0,0,0.2}
#ifdef DEBUG_MODE_FULL
    #define ICON(NAME) QUOTE(P:\MikeForceUtilities\addons\ui\data\NAME)
#else
    #define ICON(NAME) QUOTE(\z\TER_MFU\addons\ui\data\NAME)
#endif

//--- IDDs and IDCs
#define IDD_RSCDISPLAYWHITELISTEDARSENAL 202105
	#define IDC_RSCDISPLAYWHITELISTEDARSENAL_TOOLBAR 100
        #define IDC_RSCDISPLAYWHITELISTEDARSENAL_TOOLBAR_NEW 200
		#define IDC_RSCDISPLAYWHITELISTEDARSENAL_TOOLBAR_OPEN 201
		#define IDC_RSCDISPLAYWHITELISTEDARSENAL_TOOLBAR_SAVE 202
        #define IDC_RSCDISPLAYWHITELISTEDARSENAL_TOOLBAR_EXPORT 203
	#define IDC_RSCDISPLAYWHITELISTEDARSENAL_DISPLAYNAMEEDITBOX 101
    #define IDC_RSCDISPLAYWHITELISTEDARSENAL_CONFIGNAME 107
	#define IDC_RSCDISPLAYWHITELISTEDARSENAL_SECTIONS 102
	#define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP 103
        #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP_GROUPITEM 10000
            #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP_GROUPITEM_CLASS 10100
            #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP_GROUPITEM_RANKEAST 10101
            #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP_GROUPITEM_RANKWEST 10102
            #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP_GROUPITEM_RANKINDEPENDENT 10103
            #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP_GROUPITEM_RANKCIVILIAN 10104
            #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP_GROUPITEM_DELETE 10105
    #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUPLOG 106
        #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUPLOG_LOG 400
    #define IDC_RSCDISPLAYWHITELISTEDARSENAL_ADD 105
    #define IDC_RSCDISPLAYWHITELISTEDARSENAL_COPYLOG 108
    #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUPOPEN 104
        #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUPOPEN_LIST 300
        #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUPOPEN_INFO 301
        #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUPOPEN_LOAD 302
    

