#define COMPONENT ui
#include "\z\TER_MFU\addons\main\script_mod.hpp"

#define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE

#ifdef DEBUG_ENABLED_UI
    #define DEBUG_MODE_FULL
#endif
    #ifdef DEBUG_SETTINGS_OTHER
    #define DEBUG_SETTINGS DEBUG_SETTINGS_UI
#endif

#include "\z\TER_MFU\addons\main\script_macros.hpp"
#include "\z\TER_MFU\addons\main\script_macros_common.hpp"

#include "\a3\3den\UI\resincl.inc"
#include "\a3\3den\UI\macros.inc"
//--- Additional positions:
#define W_DISPLAY 140
#define H_DISPLAY (WINDOW_HAbs - 15 * GRID_H)
#define X_DISPLAY CENTER_X - 0.5 * W_DISPLAY * GRID_W
#define Y_DISPLAY CENTER_Y - 0.5 * WINDOW_HAbs + 10 * GRID_H

#define UI_SCRIPT(NAME) NAME##_script
#ifdef DEBUG_MODE_FULL
    #define INIT_DISPLAY_FUNCTION(NAME) compileScript [QUOTE(z\TER_MFU\addons\ui\scripts\NAME.sqf)]
    #define INIT_DISPLAY(NAME,PATH) \
        onLoad = ["onLoad",_this,#NAME,'##PATH##'] call INIT_DISPLAY_FUNCTION(NAME); \
        onUnload = ["onUnload",_this,#NAME,'##PATH##'] call INIT_DISPLAY_FUNCTION(NAME);
    #define INIT_CONTROL(NAME,PATH) \
        scriptName = ##NAME##;\
        scriptPath = ##PATH##;\
        onLoad = ["onLoad",_this,#NAME,'##PATH##',false] call INIT_DISPLAY_FUNCTION(NAME); \
        onUnload = ["onUnload",_this,#NAME,'##PATH##',false] call INIT_DISPLAY_FUNCTION(NAME);
    #define UI_SCRIPT(NAME) INIT_DISPLAY_FUNCTION(NAME)
#endif

#define FNC_DISPLAY_LOG (missionNamespace getVariable "TER_MFU_fnc_displayLog")

#define COLOR_DEBUG {1,0,0,0.2}
#ifdef DEBUG_MODE_FULL
    #define ICON(NAME) QUOTE(P:\MikeForceUtilities\addons\ui\data\NAME)
#else
    #define ICON(NAME) QUOTE(\z\TER_MFU\addons\ui\data\NAME)
#endif

//--- IDDs and IDCs
#define IDC_TERMFU_GROUPLOG 5050
#define IDC_TERMFU_GROUPLOG_LOG 50501 // Used for log messages. Must be a CT_STRUCTURED_TEXT control

#define IDD_RSCDISPLAYWHITELISTEDARSENAL 210513
	#define IDC_RSCDISPLAYWHITELISTEDARSENAL_TOOLBAR 100
        #define IDC_RSCDISPLAYWHITELISTEDARSENAL_TOOLBAR_NEW 200
		#define IDC_RSCDISPLAYWHITELISTEDARSENAL_TOOLBAR_OPEN 201
		#define IDC_RSCDISPLAYWHITELISTEDARSENAL_TOOLBAR_SAVE 202
        #define IDC_RSCDISPLAYWHITELISTEDARSENAL_TOOLBAR_EXPORT 203
	#define IDC_RSCDISPLAYWHITELISTEDARSENAL_DISPLAYNAMEEDITBOX 101
    #define IDC_RSCDISPLAYWHITELISTEDARSENAL_CONFIGNAME 107
	#define IDC_RSCDISPLAYWHITELISTEDARSENAL_SECTIONS 102
	#define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP 103
        #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP_GROUPITEM 10000
            #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP_GROUPITEM_CLASS 10100
            #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP_GROUPITEM_RANKEAST 10101
            #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP_GROUPITEM_RANKWEST 10102
            #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP_GROUPITEM_RANKINDEPENDENT 10103
            #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP_GROUPITEM_RANKCIVILIAN 10104
            #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUP_GROUPITEM_DELETE 10105
    #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUPLOG IDC_TERMFU_GROUPLOG
        #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUPLOG_LOG IDC_TERMFU_GROUPLOG_LOG
    #define IDC_RSCDISPLAYWHITELISTEDARSENAL_ADD 105
    #define IDC_RSCDISPLAYWHITELISTEDARSENAL_COPYLOG 108
    #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUPOPEN 104
        #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUPOPEN_LIST 300
        #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUPOPEN_INFO 301
        #define IDC_RSCDISPLAYWHITELISTEDARSENAL_GROUPOPEN_LOAD 302
    
#define IDD_RSCDISPLAYVEHICLERESPAWNINFO 210514
    #define IDC_RSCDISPLAYVEHICLERESPAWNINFO_NEW 100
    #define IDC_RSCDISPLAYVEHICLERESPAWNINFO_OPEN 101
    #define IDC_RSCDISPLAYVEHICLERESPAWNINFO_EXPORT 102
    #define IDC_RSCDISPLAYVEHICLERESPAWNINFO_GROUPRESPAWNS 103
    #define IDC_RSCDISPLAYVEHICLERESPAWNINFO_MENUSTRIP 104

#define IDC_CTRLHASHMAPVIEWER 210515
    #define IDC_CTRLHASHMAPVIEWER_TITLEDUMMY 15000
    #define IDC_CTRLHASHMAPVIEWER_TITLE 15001
    #define IDC_CTRLHASHMAPVIEWER_HASHMAP 15002
    #define IDC_CTRLHASHMAPVIEWER_OK 15003
    #define IDC_CTRLHASHMAPVIEWER_CANCEL 15004
